#!/bin/sh
export TWITTER_CONSUMER_KEY=
echo $TWITTER_CONSUMER_KEY

export TWITTER_CONSUMER_SECRET=
echo $TWITTER_CONSUMER_SECRET

export TWITTER_ACCESS_TOKEN=
echo $TWITTER_ACCESS_TOKEN

export TWITTER_ACCESS_SECRET=
echo $TWITTER_ACCESS_SECRET
